solves error log issue
It was difficult to find an actual error while creating driver instance because it was emitting an actual error message.

Earlier: 
```
com.qmetry.qaf.automation.core.AutomationError: Expected condition failed: Unable to create driver instance in 1st attempt with retry timeout of 0 seconds. You can check/set value of 'driver.init.retry.timeout' appropriately to set retry timeout on driver initialization failure. (tried for 0 second(s) with 10 SECONDS interval)
java.lang.reflect.InvocationTargetException
...
Driver info: driver.version: unknown
	at com.qmetry.qaf.automation.ui.UiDriverFactory.getDriverObj(UiDriverFactory.java:263)
...
```

Now 
```
org.openqa.selenium.WebDriverException: Connection refused (Connection refused)
...
Driver info: driver.version: AndroidDriver
	at com.qmetry.qaf.automation.ui.UiDriverFactory.getDriverObj(UiDriverFactory.java:263)
```